dev:
	RUSTFLAGS="-A unused_imports -A dead_code -A unreachable_code" cargo build

release:
	cargo build

clean:
	cargo clean

run:
	RUSTFLAGS="-A unused_imports -A dead_code -A unreachable_code" cargo run